name: Build and test project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
